In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("data.csv")
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [4]:
 df.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [5]:
df.shape

(100000, 9)

In [6]:
#gender in string
#smoking_history in string
df["gender"].unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [7]:
df["smoking_history"].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
lbl = LabelEncoder()
df["gender"] = lbl.fit_transform(df["gender"])
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,never,25.19,6.6,140,0
1,0,54.0,0,0,No Info,27.32,6.6,80,0
2,1,28.0,0,0,never,27.32,5.7,158,0
3,0,36.0,0,0,current,23.45,5.0,155,0
4,1,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,0,80.0,0,0,No Info,27.32,6.2,90,0
99996,0,2.0,0,0,No Info,17.37,6.5,100,0
99997,1,66.0,0,0,former,27.83,5.7,155,0
99998,0,24.0,0,0,never,35.42,4.0,100,0
99999,0,57.0,0,0,current,22.43,6.6,90,0

In [9]:
df["gender"].unique()

array([0, 1, 2])

In [10]:
from sklearn.preprocessing import LabelEncoder
lbl = LabelEncoder()
df["gender"] = lbl.fit_transform(df["gender"])

In [11]:
df["gender"].unique()

array([0, 1, 2])

In [12]:
df["smoking_history"].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [13]:
smoking_map = {
    'never': 0,
    'former': 1,
    'not current': 2,
    'current': 3,
    'ever': 2,      # depends on your definition
    'No Info': -1
}

df['smoking_history'] = df['smoking_history'].map(smoking_map)

In [14]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,0,25.19,6.6,140,0
1,0,54.0,0,0,-1,27.32,6.6,80,0
2,1,28.0,0,0,0,27.32,5.7,158,0
3,0,36.0,0,0,3,23.45,5.0,155,0
4,1,76.0,1,1,3,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,0,80.0,0,0,-1,27.32,6.2,90,0
99996,0,2.0,0,0,-1,17.37,6.5,100,0
99997,1,66.0,0,0,1,27.83,5.7,155,0
99998,0,24.0,0,0,0,35.42,4.0,100,0
99999,0,57.0,0,0,3,22.43,6.6,90,0

In [15]:
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level']] = scaler.fit_transform(
           df[['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
               'bmi', 'HbA1c_level', 'blood_glucose_level']]
       )
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,-0.841047,1.692704,-0.284439,4.936379,-0.173273,-0.321056,1.001706,0.047704,0
1,-0.841047,0.538006,-0.284439,-0.202578,-0.950419,-0.000116,1.001706,-1.426210,0
2,1.187234,-0.616691,-0.284439,-0.202578,-0.173273,-0.000116,0.161108,0.489878,0
3,-0.841047,-0.261399,-0.284439,-0.202578,2.158166,-0.583232,-0.492690,0.416183,0
4,1.187234,1.515058,3.515687,4.936379,2.158166,-1.081970,-0.679490,0.416183,0
...,...,...,...,...,...,...,...,...,...
99995,-0.841047,1.692704,-0.284439,-0.202578,-0.950419,-0.000116,0.628107,-1.180558,0
99996,-0.841047,-1.771388,-0.284439,-0.202578,-0.950419,-1.499343,0.908306,-0.934905,0
99997,1.187234,1.070944,-0.284439,-0.202578,0.603874,0.076729,0.161108,0.416183,0
99998,-0.841047,-0.794336,-0.284439,-0.202578,-0.173273,1.220361,-1.426688,-0.934905,0
99999,-0.841047,0.671241,-0.284439,-0.202578,2.158166,-0.736922,1.001706,-1.180558,0

In [17]:
X = df[['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level']]
X

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
0,-0.841047,1.692704,-0.284439,4.936379,-0.173273,-0.321056,1.001706,0.047704
1,-0.841047,0.538006,-0.284439,-0.202578,-0.950419,-0.000116,1.001706,-1.426210
2,1.187234,-0.616691,-0.284439,-0.202578,-0.173273,-0.000116,0.161108,0.489878
3,-0.841047,-0.261399,-0.284439,-0.202578,2.158166,-0.583232,-0.492690,0.416183
4,1.187234,1.515058,3.515687,4.936379,2.158166,-1.081970,-0.679490,0.416183
...,...,...,...,...,...,...,...,...
99995,-0.841047,1.692704,-0.284439,-0.202578,-0.950419,-0.000116,0.628107,-1.180558
99996,-0.841047,-1.771388,-0.284439,-0.202578,-0.950419,-1.499343,0.908306,-0.934905
99997,1.187234,1.070944,-0.284439,-0.202578,0.603874,0.076729,0.161108,0.416183
99998,-0.841047,-0.794336,-0.284439,-0.202578,-0.173273,1.220361,-1.426688,-0.934905
99999,-0.841047,0.671241,-0.284439,-0.202578,2.158166,-0.736922,1.001706,-1.180558

In [18]:
y = df[["diabetes"]]
y

       diabetes
0             0
1             0
2             0
3             0
4             0
...         ...
99995         0
99996         0
99997         0
99998         0
99999         0

[100000 rows x 1 columns]

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [20]:
X_train

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
75220,1.187234,1.381824,-0.284439,-0.202578,0.603874,-0.384340,-1.893686,-1.426210
48955,1.187234,1.692704,-0.284439,-0.202578,-0.173273,-0.409955,0.161108,0.170530
44966,-0.841047,-0.172576,-0.284439,-0.202578,1.381020,-0.450637,-1.426688,0.489878
13568,-0.841047,-0.705514,-0.284439,-0.202578,1.381020,-1.273329,-0.492690,-0.934905
92727,-0.841047,0.848886,3.515687,-0.202578,2.158166,-0.785138,-0.959689,-1.303384
...,...,...,...,...,...,...,...,...
6265,1.187234,0.315949,-0.284439,-0.202578,-0.173273,0.852711,0.161108,-1.426210
54886,-0.841047,-1.194039,-0.284439,-0.202578,-0.173273,0.117412,-0.492690,0.514444
76820,1.187234,0.005069,-0.284439,-0.202578,-0.173273,-0.177913,0.254508,-1.303384
860,-0.841047,-0.216988,-0.284439,-0.202578,-0.173273,-0.355711,0.628107,0.489878
15795,-0.841047,-0.838748,-0.284439,-0.202578,-0.173273,0.100837,-0.492690,0.514444

In [21]:
X_test

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
75721,-0.841047,-1.282862,-0.284439,-0.202578,-0.950419,-0.979511,0.254508,-0.296209
80184,-0.841047,-1.726976,-0.284439,-0.202578,-0.950419,-0.952389,-0.492690,0.170530
19864,1.187234,0.937709,-0.284439,-0.202578,0.603874,-0.301468,-1.893686,1.521618
76699,-0.841047,-1.771388,-0.284439,-0.202578,-0.173273,-1.490303,0.534707,-0.296209
92991,-0.841047,-0.394634,-0.284439,-0.202578,1.381020,1.922512,0.628107,1.521618
...,...,...,...,...,...,...,...,...
32595,-0.841047,0.093892,-0.284439,-0.202578,1.381020,-0.809247,0.441307,0.514444
29313,1.187234,0.848886,3.515687,-0.202578,0.603874,2.208797,-1.893686,-1.180558
37862,-0.841047,0.315949,-0.284439,-0.202578,-0.173273,-0.122163,-0.679490,-0.934905
53421,1.187234,1.381824,-0.284439,4.936379,-0.950419,-0.000116,1.001706,-0.934905
42410,-0.841047,0.049481,-0.284439,-0.202578,-0.173273,-0.521455,0.254508,0.170530

In [22]:
from sklearn.linear_model import LogisticRegression
model  = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [23]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [24]:
y_pred = pd.DataFrame(y_pred, columns=['prediction'])
y_pred

       prediction
0               0
1               0
2               0
3               0
4               0
...           ...
19995           0
19996           0
19997           0
19998           0
19999           0

[20000 rows x 1 columns]

In [25]:
y_test

       diabetes
75721         0
80184         0
19864         0
76699         0
92991         1
...         ...
32595         0
29313         0
37862         0
53421         0
42410         0

[20000 rows x 1 columns]

In [26]:
result =  pd.concat((y_test.reset_index(drop=True),y_pred.reset_index(drop=True)),axis=1)
result

       diabetes  prediction
0             0           0
1             0           0
2             0           0
3             0           0
4             1           0
...         ...         ...
19995         0           0
19996         0           0
19997         0           0
19998         0           0
19999         0           0

[20000 rows x 2 columns]

In [27]:
from  sklearn.metrics import accuracy_score
score = accuracy_score(result["diabetes"],result["prediction"])
score

0.959

In [28]:
myinput = [[1, 55, 1, 1, 4, 32, 9, 90]]
myinput

[[1, 55, 1, 1, 4, 32, 9, 90]]

In [29]:
columns = ['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level']
columns

['gender',
 'age',
 'hypertension',
 'heart_disease',
 'smoking_history',
 'bmi',
 'HbA1c_level',
 'blood_glucose_level']

In [30]:
data = pd.DataFrame(data = myinput,columns = columns)
data

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
0,1,55,1,1,4,32,9,90

In [31]:
data_scaled = scaler.transform(data)
data_scaled

array([[ 1.18723364,  0.58241785,  3.51568677,  4.93637859,  2.93531257,
         0.70504882,  3.2432996 , -1.18055762]])

In [38]:
result = model.predict(myinput)
result

array([1])

In [33]:
myinput = [[1, 55, 1, 1, 4, 32, 9, 90]]
columns = ['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level']
data = pd.DataFrame(data = myinput, columns = columns)
data_scaled = scaler.transform(data)
result = model.predict(data_scaled)
if result[0] == 1:
    print("Person in diabetic")
else:
    print("Person in not diabetic")

Person in diabetic

In [34]:
myinput = [[0, 30, 0, 0, 0, 22, 5.2, 95]]
columns = ['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level']
data = pd.DataFrame(data=myinput, columns=columns)
data_scaled = scaler.transform(data)
result = model.predict(data_scaled)

if result[0] == 1:
    print("Person is diabetic")
else:
    print("Person is not diabetic")

Person is not diabetic

In [36]:
import pickle as pkl
pkl.dump(scaler,open('scaler.pkl','wb'))
pkl.dump(model,open('model.pkl','wb'))

In [37]:
df.to_csv("diabetic.csv")

In [3]:

print(np.__version__)
print(pd.__version__)

2.1.3
2.2.3

In [5]:
import sklearn
print(sklearn.__version__)

1.6.1

In [6]:
import streamlit 
print(streamlit.__version__)

1.45.1